apiVersion: v1
kind: Namespace
metadata:
  name: sosreport-operator
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sosreport-og
  namespace: sosreport-operator
  # spec:
  #  targetNamespaces:
  #- "sosreport-operator"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sosreport-operator-subscription
  namespace: sosreport-operator
spec:
  channel: alpha
  name: sosreport-operator
  source: sosreport-operator-manifests
  sourceNamespace: openshift-marketplace
