apiVersion: v1
kind: ConfigMap
metadata:
  name: sosreport-upload-configuration
  # namespace: sosreport-operator-system
data:
  upload-method: "none" # case|ftp|nfs
  case-number: "00000000" # must be set for upload-method "case"
  obfuscate: "false" # options for upload-method "case"
  nfs-share: "kind:/nfs" # must be set for nfs
  nfs-options: "" # optional for nfs
  ftp-server: "ftp://kind"
