apiVersion: v1
kind: ConfigMap
metadata:
  name: sosreport-development-configuration
  # namespace: sosreport-operator-system
data:
  sosreport-image: "kind:5000/sosreport-centos:latest"
  sosreport-command: "bash -x /scripts/entrypoint.sh"
  simulation-mode: "false"
  debug: "true"
  image-pull-policy: "" # "", "Always", "IfNotPresent", "Never"
