apiVersion: support.openshift.io/v1alpha1
kind: Sosreport
metadata:
  name: sosreport-sample
  #namespace: sosreport-operator-system
spec:
   tolerations:
   - key: node-role.kubernetes.io/master
     effect: NoSchedule
#  nodeSelector:
#    type: worker
#  nodeSelector:
#    kubernetes.io/hostname: kind-worker2
