# Need SETFCAP to install specific RPMs like uputils
# https://github.com/containers/podman/issues/5364
# oc adm policy add-scc-to-user privileged -z default
# mimic: command: podman run -it --name toolbox- --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=toolbox- -e IMAGE=registry.redhat.io/rhel8/support-tools:latest -v /run:/run -v /var/log:/var/log -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -v /:/host registry.redhat.io/rhel8/support-tools:latest
apiVersion: batch/v1
kind: Job
metadata:
  name: sosreport-job
spec:
  template:
    spec:
      hostIPD: true
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - name: sosreport
        image: alpine
        # imagePullPolicy: Always  # with :latest -> Always, otherwise IfNotPresent
        command:
          - "sleep"
          - "60"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /run
            name: run
          - mountPath: /var/log
            name: varlog
          - mountPath: /etc/machine-id
            name: machineid
#          - mountPath: /etc/localtime
#            name: localtime
          - mountPath: /host
            name: host
      volumes:
      - name: run
        hostPath:
          path: /run/
          type: Directory
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: machineid
        hostPath:
          path: /etc/machine-id
          type: File
#      - name: localtime
#        hostPath:
#          path: /etc/localtime
#          type: File
      - name: host
        hostPath:
          path: /
          type: Directory
