install-fedora:
	bash -x openshift_install_prerequisites_fedora.sh

enable-fedora:
	bash -x openshift_enable_prerequisites_fedora.sh

disable-fedora:
	bash -x openshift_disable_prerequisites_fedora.sh

install-snc:
	bash -x openshift_install_snc.sh
