# This shouldn't be used by the operator, but it's here for testing
# different settings for the sosreport image
# Need SETFCAP to install specific RPMs like uputils
# https://github.com/containers/podman/issues/5364
# oc adm policy add-scc-to-user privileged -z default
# mimic: command: podman run -it --name toolbox- --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=toolbox- -e IMAGE=registry.redhat.io/rhel8/support-tools:latest -v /run:/run -v /var/log:/var/log -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -v /:/host registry.redhat.io/rhel8/support-tools:latest
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sosreport-deployment-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
